name: control_pad
description: A virtual pad with joystick controller and configurable buttons.
version: 1.1.1+1
homepage: https://github.com/artrmz/flutter_control_pad

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
